spring.application.name=ServiceRegistry

eureka.instance.hostname=localhost

# Disable Eureka client registration and fetching registry
# This is because this application is only acting as a Eureka server, not a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: Set the port for the Eureka server
server.port=8761

