spring.application.name=rating-service
server.port=8083
server.servlet.context-path=/rating-service

spring.datasource.url=jdbc:postgresql://localhost:5432/rating-service
spring.datasource.username=postgres
spring.datasource.password=credable
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Eureka Client Configuration
# It's important to set the prefer-ip-address to true, otherwise eureka will register the service with its hostname which might not be resolvable in some environments.
# This is especially important in containerized environments like Docker or Kubernetes where the hostname might not be easily resolvable.
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka/

spring.config.import= configserver:http://localhost:8085

# Resilience4j Configuration
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.slowCallDurationThreshold=2000
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.recordExceptions=java.lang.Exception
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.ignoreExceptions=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.ratingServiceCircuitBreaker.slidingWindowType=COUNT_BASED



management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health
management.endpoint.health.show-components=always
logging.level.org.springframework.security=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/oauth-test